#  runtime: python27
#  api_version: 1
#  threadsafe: false

#  handlers:
#  - url: /
#    script: test.app

#application: your-app-identifier 
#version: 1
#runtime: python27
#api_version: 1 
#threadsafe: true

#handlers:
#- url: /.*
 # script: test.app

runtime: python27
api_version: 1
threadsafe: false

handlers: 
- url: /
  script: test.app
